import { Link, useRouterState } from "@tanstack/react-router";
import {
  Activity,
  BellRing,
  Bolt,
  Cpu,
  Gauge,
  History,
  LayoutDashboard,
  LineChart,
  Menu,
  PlugZap,
  Settings as SettingsIcon,
  Sliders,
  User,
  LogOut,
  Wrench,
  Workflow,
  Database,
  Server,
  Radio,
} from "lucide-react";
import { useState, type ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { useEnergy } from "@/lib/energy/store";
import { fmtClock, fmtW } from "@/lib/energy/format";

const NAV = [
  { to: "/", label: "Overview", icon: LayoutDashboard, hint: "System dashboard & key metrics" },
  { to: "/live", label: "Live Telemetry", icon: Activity, hint: "ESP32 hardware sensor stream" },
  { to: "/appliances", label: "Appliances", icon: PlugZap, hint: "Connected appliance models" },
  { to: "/analytics", label: "Cognitive Analysis", icon: Gauge, hint: "ATF, ERI, DSC, CDI & UBD metrics" },
  { to: "/predictions", label: "Predictions", icon: LineChart, hint: "ML power forecasting" },
  { to: "/control", label: "Control Center", icon: Sliders, hint: "RL actions & relay interlocks" },
  { to: "/history", label: "History", icon: History, hint: "PostgreSQL telemetry & UK-DALE logs" },
  { to: "/alerts", label: "Alerts & Safety", icon: BellRing, hint: "Real-time safety events" },
  { to: "/devices", label: "IoT Devices", icon: Cpu, hint: "ESP32 node & pinout status" },
  { to: "/architecture", label: "System Architecture", icon: Workflow, hint: "Closed-loop system pipeline" },
  { to: "/settings", label: "Settings", icon: SettingsIcon, hint: "Tariff, budget & API configuration" },
] as const;

function NavList({ onNavigate }: { onNavigate?: () => void }) {
  const pathname = useRouterState({ select: (s) => s.location.pathname });
  const { alerts } = useEnergy();
  const unread = alerts.filter((a) => !a.acknowledged).length;

  return (
    <nav aria-label="Main" className="flex flex-col gap-1 p-3">
      {NAV.map((item) => {
        const active = pathname === item.to;
        const Icon = item.icon;
        return (
          <Link
            key={item.to}
            to={item.to}
            onClick={onNavigate}
            aria-current={active ? "page" : undefined}
            className={cn(
              "group flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors",
              active
                ? "bg-sidebar-primary text-sidebar-primary-foreground"
                : "text-sidebar-foreground/80 hover:bg-sidebar-accent hover:text-sidebar-accent-foreground",
            )}
          >
            <Icon className="size-4 shrink-0" aria-hidden="true" />
            <span className="truncate">{item.label}</span>
            {item.to === "/alerts" && unread > 0 ? (
              <Badge className="ml-auto bg-destructive text-destructive-foreground">{unread}</Badge>
            ) : null}
          </Link>
        );
      })}
    </nav>
  );
}

function Brand() {
  return (
    <div className="flex items-center gap-3 border-b border-sidebar-border px-4 py-4">
      <div className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary text-primary-foreground">
        <Bolt className="size-5" aria-hidden="true" />
      </div>
      <div className="min-w-0">
        <p className="truncate text-sm font-semibold tracking-tight">Cognitive Energy</p>
        <p className="truncate text-xs text-muted-foreground">Optimization System</p>
      </div>
    </div>
  );
}

export function DemoModeBadge() {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Badge
          variant="outline"
          tabIndex={0}
          className="border-warning/40 bg-warning/15 text-warning gap-1.5 font-medium"
        >
          <span className="size-1.5 rounded-full bg-warning" aria-hidden="true" />
          Demo mode · Simulated data
        </Badge>
      </TooltipTrigger>
      <TooltipContent className="max-w-64">
        All readings are generated by a built-in simulator. No hardware is physically connected.
      </TooltipContent>
    </Tooltip>
  );
}

export function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const { snapshot, ready, now, house, appliances, settings, user, logoutUser } = useEnergy();

  return (
    <div className="min-h-screen bg-background">
      <a
        href="#main"
        className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:z-50 focus:rounded-md focus:bg-primary focus:px-3 focus:py-2 focus:text-primary-foreground"
      >
        Skip to content
      </a>

      <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-sidebar-border bg-sidebar lg:flex">
        <Brand />
        <div className="flex-1 overflow-y-auto">
          <NavList />
        </div>
        <div className="border-t border-sidebar-border p-4 text-xs text-muted-foreground">
          <p className="font-medium text-foreground">
            {settings.useLiveApi && house ? house.name : `${appliances.length} demo appliance models`}
          </p>
          <p className="mt-1 font-mono text-[11px] truncate">
            {appliances.map((a) => a.name).join(" · ")}
          </p>
        </div>
      </aside>

      <div className="lg:pl-64">
        <header className="sticky top-0 z-20 flex flex-wrap items-center gap-3 border-b border-border bg-background/85 px-4 py-3 backdrop-blur sm:px-6">
          <Sheet open={open} onOpenChange={setOpen}>
            <SheetTrigger asChild>
              <Button variant="outline" size="icon" className="lg:hidden" aria-label="Open navigation">
                <Menu className="size-4" />
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="w-72 p-0">
              <SheetTitle className="sr-only">Navigation</SheetTitle>
              <Brand />
              <NavList onNavigate={() => setOpen(false)} />
            </SheetContent>
          </Sheet>

          {settings.useLiveApi ? (
            <div className="flex items-center gap-2">
              <Tooltip>
                <TooltipTrigger asChild>
                  <Badge
                    variant="outline"
                    tabIndex={0}
                    className="border-emerald-500/40 bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 gap-1.5 font-medium"
                  >
                    <span className="size-1.5 rounded-full bg-emerald-500 animate-pulse" aria-hidden="true" />
                    LIVE HARDWARE
                  </Badge>
                </TooltipTrigger>
                <TooltipContent className="max-w-64">
                  {house ? `${house.name} · ${house.location} · Connected to Render PostgreSQL Backend.` : "Connected to Live Backend."}
                </TooltipContent>
              </Tooltip>
              {snapshot.isHardwareLive ? (
                <span className="hidden xl:inline-flex items-center gap-1 text-[11px] font-mono text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
                  <Radio className="size-3" /> ESP32 NODE ONLINE
                </span>
              ) : null}
            </div>
          ) : (
            <DemoModeBadge />
          )}

          <div className="ml-auto flex items-center gap-4 text-sm">
            {user ? (
              <div className="flex items-center gap-2 bg-muted/60 px-2.5 py-1 rounded-lg border border-border/60">
                <User className="h-3.5 w-3.5 text-primary" />
                <span className="font-medium text-xs hidden sm:inline">{user.name}</span>
                <span className="font-mono text-[11px] text-primary font-bold">({user.user_id})</span>
                <Link to="/setup" className="text-xs hover:text-primary transition-colors flex items-center gap-1 ml-1" title="Run Setup Wizard">
                  <Wrench className="h-3 w-3" />
                </Link>
                <button onClick={logoutUser} className="text-xs text-muted-foreground hover:text-destructive transition-colors ml-1" title="Sign Out">
                  <LogOut className="h-3.5 w-3.5" />
                </button>
              </div>
            ) : (
              <Link to="/login" className="text-xs font-semibold text-primary hover:underline flex items-center gap-1">
                <User className="h-3.5 w-3.5" /> Sign In / Register
              </Link>
            )}
            <div className="hidden items-center gap-2 sm:flex">
              <span className="text-muted-foreground">Now</span>
              <span className="num font-semibold">{ready ? fmtW(snapshot.totalPowerW) : "—"}</span>
            </div>
            <div className="hidden items-center gap-2 md:flex">
              <span className="text-muted-foreground">Safety</span>
              <span
                className={cn(
                  "font-semibold capitalize",
                  snapshot.safety === "safe"
                    ? "text-success"
                    : snapshot.safety === "guarded"
                      ? "text-warning"
                      : "text-destructive",
                )}
              >
                {snapshot.safety}
              </span>
            </div>
            <span className="num text-xs text-muted-foreground" aria-live="off">
              {ready ? fmtClock(now) : "--:--:--"}
            </span>
          </div>
        </header>

        <main id="main" className="mx-auto w-full max-w-[1400px] px-4 py-6 sm:px-6 sm:py-8">
          <div className="flex flex-col gap-6">{children}</div>
        </main>
      </div>
    </div>
  );
}
